# .vale.ini
StylesPath = .github/vale/styles
MinAlertLevel = suggestion

# Ignore Jekyll YAML front matter
TokenIgnores = ^---(\n|.)*?---

# Folder-specific rules
[_documentation/*.md]
BasedOnStyles = Vale, Microsoft

[_docs_creation_APIs/*.md]
BasedOnStyles = Vale, Microsoft

# Ignore build output and vendor folders
Ignored = _site/**, vendor/**, node_modules/**
